# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/" # Uses default location of GitHub Workflows
  schedule:
    interval: "weekly"
  groups:
    prod-github-actions:
      dependency-type: "production"
    dev-github-actions:
      dependency-type: "development"

# Maintain dependencies for Docker
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"

# Maintain dependencies for npm in playwright
- package-ecosystem: "npm"
  directory: "/playwright/"
  schedule:
    interval: "weekly"
  groups:
    prod-minor-npm-dependencies:
      dependency-type: "production"
      update-types:
        - "minor"
        - "patch"
    dev-minor-npm-dependencies:
      dependency-type: "development"
      update-types:
        - "minor"
        - "patch"

# Maintain dependencies for npm in complete-application
- package-ecosystem: "npm"
  directory: "/complete-application/"
  schedule:
    interval: "weekly"
  groups:
    prod-minor-npm-dependencies:
      dependency-type: "production"
      update-types:
        - "minor"
        - "patch"
    dev-minor-npm-dependencies:
      dependency-type: "development"
      update-types:
        - "minor"
        - "patch"