# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

# Enable beta ecosystems to get updates for Docker Compose
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Uses default location of GitHub Workflows
    schedule:
      interval: "weekly"
    groups:
      prod-github-actions:
        dependency-type: "production"
      dev-github-actions:
        dependency-type: "development"

  # Maintain dependencies for Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "Samples/Quickstart/fusionauth/latest/" # Location of package manifests
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm in complete-application
  - package-ecosystem: "npm"
    directory: "/complete-application/"
    schedule:
      interval: "weekly"
    groups:
      prod-minor-npm-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-minor-npm-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
