name: Playwright Tests on all Github Runners
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  e2e-test:
    name: End 2 End Test
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-24.04", "ubuntu-22.04", "ubuntu-20.04" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Start FusionAuth
        uses: fusionauth/fusionauth-github-action@v1
        with:
          FUSIONAUTH_APP_KICKSTART_DIRECTORY_PATH: kickstart

      - name: Install Application
        run: npm i --prefix "./complete-application/"

      - name: Build Application
        run: npm run build --prefix "./complete-application/"

      - name: Run Application
        run: npm start --prefix "./complete-application/" &

      - name: Upload Playwright results
        uses: sonderformat-llc/c111-run-quickstart-e2e-test@main